version: 2

# FUNCIONALIDAD DE SERVER TEST
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/requirements.txt